CREATE TABLE "HRWR"."JOB_EXECUTION"
   (
   "JOB_EXECUTION_ID" NUMBER NOT NULL ENABLE,
   "PY_DATE" TIMESTAMP (6) NOT NULL ENABLE,
   "SQL_DATE" TIMESTAMP (6) NOT NULL ENABLE,
   "NODE" VARCHAR2(100) NOT NULL ENABLE,
   "TEST_NAME" VARCHAR(200) NOT NULL ENABLE,
   CONSTRAINT "JOB_EXECUTION_PK" PRIMARY KEY ("JOB_EXECUTION_ID")
);


CREATE SEQUENCE SEQ_JOB_EXECUTION_ID
  START WITH 261
  MAXVALUE 9999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 100
  ORDER;

CREATE OR REPLACE FUNCTION get_execution_id(in_date IN NUMBER)
  RETURN NUMBER IS execution_id NUMBER;
  BEGIN
      execution_id := seq_job_execution_id.nextval;
      RETURN(execution_id);
  END get_execution_id;

